#!/bin/sh
# Wait for mitmproxy CA cert (generated by proxy on first start)
CERT="/opt/proxy-ca/mitmproxy-ca-cert.pem"
echo "[vault] Waiting for proxy CA certificate..."
for i in $(seq 1 30); do
    [ -f "$CERT" ] && break
    sleep 1
done
if [ ! -f "$CERT" ]; then
    echo "[vault] WARNING: Proxy CA cert not found after 30s. TLS verification may fail."
fi
exec "$@"
