#!/bin/sh
# OpenClaw-Vault entrypoint wrapper
# 1. Copy hardening config to ~/.openclaw/openclaw.json (tmpfs shadows image layer)
# 2. Wait for mitmproxy CA cert (generated by proxy on first start)
# 3. Exec into OpenClaw

# --- Copy hardening config to ~/.openclaw ---
# OpenClaw reads config from ~/.openclaw/openclaw.json (JSON5 format).
# The compose tmpfs on /home/vault/.openclaw shadows the image layer,
# so we must copy the config at startup.
CONFIG_SRC="/opt/openclaw-hardening.json5"
CONFIG_DST="/home/vault/.openclaw/openclaw.json"
if [ -f "$CONFIG_SRC" ]; then
    mkdir -p "$(dirname "$CONFIG_DST")"
    cp "$CONFIG_SRC" "$CONFIG_DST"
    echo "[vault] Hardening config installed at $CONFIG_DST"
else
    echo "[vault] ERROR: Hardening config not found at $CONFIG_SRC" >&2
    exit 1
fi

# --- Wait for mitmproxy CA cert (must be complete PEM, not partially written) ---
CERT="/opt/proxy-ca/mitmproxy-ca-cert.pem"
echo "[vault] Waiting for proxy CA certificate..."
for i in $(seq 1 60); do
    if [ -f "$CERT" ] && grep -q "END CERTIFICATE" "$CERT" 2>/dev/null; then
        echo "[vault] CA certificate found."
        break
    fi
    sleep 1
done
if [ ! -f "$CERT" ] || ! grep -q "END CERTIFICATE" "$CERT" 2>/dev/null; then
    echo "[vault] ERROR: Proxy CA cert not found or incomplete after 60s. Aborting." >&2
    exit 1
fi

# --- Create auth profile with placeholder key ---
# OpenClaw requires an API key in its auth store to even attempt API calls.
# We give it a DUMMY placeholder. The vault-proxy sidecar replaces it with
# the real key at the network layer (header injection). The agent never
# sees the real key — only this placeholder.
AUTH_DIR="/home/vault/.openclaw/agents/main/agent"
mkdir -p "$AUTH_DIR"
cat > "$AUTH_DIR/auth-profiles.json" << 'AUTHEOF'
{
  "profiles": {
    "anthropic:api": {
      "provider": "anthropic",
      "type": "api_key",
      "key": "sk-ant-api03-placeholder-vault-proxy-will-inject-real-key-placeholder"
    }
  },
  "order": {
    "anthropic": ["anthropic:api"]
  }
}
AUTHEOF
echo "[vault] Auth profile installed (placeholder key — real key injected by proxy)"

echo "[vault] Starting OpenClaw..."
exec "$@"
